name: wallet_words
description: Flutter library for building input fields with InputChips as input options.
version: 2.0.0
homepage: https://github.com/jorger5/wallet_words
maintainer: Jorge Rincon

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0


flutter:
