name: wallet_words
description: Flutter library for building input fields with InputChips as input options.
version: 1.1.3
homepage: https://github.com/jorger5/wallet_words
maintainer: Jorge Rincon

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1


flutter:
